### ISSUE TITLE
Learn how to play

### ISSUE THREAD

**Issue by gregberge** [smooth-code/react-quiz#3]
- [x] Create Timer component (#10)
- [x] Create Progress component (#8)
- [x] Create Question component (#12)
- [x] Create Answer component (#13)
- [x] Create NextButton component (#14)
- [x] Create Quiz component (#15)
- [ ] Create Tutorial component (#19)
